### ISSUE TITLE
spawn child process error

### ISSUE THREAD

**Issue by fengmk2** [aleafs/itier-client#7]
I found a `itier` client uncaughtException throw out:

``` javascript
timers.js:96
            if (!process.listeners('uncaughtException').length) throw e;
                                                                      ^
Error: spawn ENOMEM
    at errnoException (child_process.js:483:11)
    at ChildProcess.spawn (child_process.js:446:11)
    at child_process.js:342:9
    at /home/admin/x/target/x/node_modules/itier/lib/http-client.js:17:15
    at /home/admin/x/target/x/node_modules/itier/lib/http-client.js:41:5
    at Array.forEach (native)
    at /home/admin/x/target/x/node_modules/itier/lib/http-client.js:40:14
    at Object
._onTimeout (/home/admin/x/target/x/node_modules/itier/lib/http-client.js:51:11)
    at Timer.ontimeout (timers.js:94:19)
[master] new worker forked (19578:/home/admin/x/target/x/app.js) for 7001, 12200
```

**Comment by aleafs** [comment]
fixed

**Comment by guss77** [comment]
BTW, how was this fixed? I have a similar issue with a different library and I think that discussing the solution here could help me there.

Tia
