### ISSUE TITLE
add no avaible host list Error

### ISSUE THREAD

**Issue by fengmk2** [aleafs/itier-client#9]
当所有节点都不可用的时候，增加特殊的错误信息返回。

```
2012-08-11 00:00:02 nodejs.ITierErrorException: ITierErrorException: no avaible host list for :ots
at Itier.query (/home/admin/xxx/target/xxx/node_modules/itier/lib/itier-client.js:156:19)
at IncomingMessage.Client._call.timer (/home/admin/xxx/target/xxx/node_modules/itier/lib/http-client.js:201:7)
at IncomingMessage.EventEmitter.emit (events.js:115:20)
at IncomingMessage._emitEnd (http.js:366:10)
at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
at Socket.socketOnData [as ondata] (http.js:1356:20)
at TCP.onread (net.js:404:27)
```

**Comment by fengmk2** [comment]
区分开来，方便监控统计。

**Comment by fengmk2** [comment]
return header['x-itier-realhost'];

**Comment by aleafs** [comment]
这都能被你发现

**Comment by fengmk2** [comment]
哈哈，从log中发现的

Sent from my iPhone

On 2012-8-11, at 20:04, aleafs notifications@github.com wrote:

这都能被你发现

—
Reply to this email directly or view it on
GitHubhttps://github.com/aleafs/itier-client/issues/9#issuecomment-7666273.
